"clean:cli" = "cargo clean -p odict-cli"

["build:cli"]
run = "cargo build -p odict-cli"
alias = "build"
sources = ["cli/src/**/*.rs", "cli/Cargo.toml"]
outputs = { auto = true }

["run:cli"]
run = "cargo run -p odict-cli"
alias = "run"
